use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let src_dir = Path::new("src");

    // ── 1. Plugin manifests (from frontend addons) ──
    let manifest_dir = Path::new("../src/addons");
    let manifest_dest = Path::new(&out_dir).join("plugin_manifests.rs");

    let mut manifests = Vec::new();
    if manifest_dir.exists() {
        for entry in fs::read_dir(manifest_dir).unwrap().flatten() {
            let path = entry.path();
            if path.is_dir() {
                let manifest_path = path.join("manifest.json");
                if manifest_path.exists() {
                    let content = fs::read_to_string(&manifest_path).unwrap();
                    manifests.push(content);
                }
            }
        }
    }

    let mut manifest_code = String::from("/// Embedded plugin manifests (generated by build.rs)\n");
    manifest_code.push_str("fn embedded_plugin_manifests() -> Vec<serde_json::Value> {\n");
    manifest_code.push_str("    vec![\n");
    for m in &manifests {
        manifest_code.push_str(&format!("        serde_json::from_str(r#\"{}\"#).unwrap(),\n", m.trim()));
    }
    manifest_code.push_str("    ]\n");
    manifest_code.push_str("}\n");
    fs::write(&manifest_dest, manifest_code).unwrap();

    // ── 2. Auto-discover Rust plugin modules ──
    // Non-plugin modules that should not be auto-discovered
    let skip = [
        "target", ".git", ".idea", ".vscode",
        "acrylic", "plugins", "settings", "tray", "window_attach",
    ];

    let mut plugin_names: Vec<String> = Vec::new();

    if src_dir.exists() {
        for entry in fs::read_dir(src_dir).unwrap().flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            if skip.contains(&name.as_str()) {
                continue;
            }
            let mod_rs = path.join("mod.rs");
            if !mod_rs.exists() {
                continue;
            }
            plugin_names.push(name);
        }
    }
    plugin_names.sort();

    let plugin_dest = Path::new("src").join("_plugins.rs");

    // Generate mod declarations
    let mut code = String::from("// Auto-generated plugin registrations (generated by build.rs)\n// Do not edit manually.\n\n");
    for name in &plugin_names {
        code.push_str(&format!("#[path = \"{}/mod.rs\"]\npub mod {};\n", name, name));
    }

    // Generate setup calls
    code.push_str("\npub fn setup_all(app: &tauri::AppHandle) {\n");
    for name in &plugin_names {
        code.push_str(&format!("    {}::setup(app);\n", name));
    }
    code.push_str("}\n");

    // Generate a const string listing all plugin commands (for documentation)
    // The actual command list is generated in a separate file
    let mut commands = Vec::new();
    for name in &plugin_names {
        let mod_path = src_dir.join(name).join("mod.rs");
        let content = fs::read_to_string(&mod_path).unwrap_or_default();
        let mut in_command = false;
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed == "#[tauri::command]" {
                in_command = true;
                continue;
            }
            if in_command {
                in_command = false;
                if let Some(fn_name) = extract_fn_name(trimmed) {
                    commands.push(format!("{}::{}", name, fn_name));
                }
            }
        }
    }
    code.push_str(&format!("\n// Discovered plugin commands: {:?}\n", commands));

    // Only write if changed (avoid unnecessary rebuilds)
    let existing = fs::read_to_string(&plugin_dest).unwrap_or_default();
    if existing != code {
        fs::write(&plugin_dest, code).unwrap();
    }

    // Re-run if any plugin mod.rs changes
    for name in &plugin_names {
        println!("cargo:rerun-if-changed=src/{}/mod.rs", name);
    }
    println!("cargo:rerun-if-changed=src/");

    tauri_build::build()
}

/// Extract function name from a line like `pub async fn name(` or `pub fn name(`
fn extract_fn_name(line: &str) -> Option<String> {
    let line = line.trim_start();
    // Must start with "pub" and contain "fn"
    if !line.starts_with("pub ") || !line.contains("fn ") {
        return None;
    }
    let after_fn = line.split("fn ").nth(1)?;
    let name = after_fn.split('(').next()?.trim();
    if name.is_empty() {
        return None;
    }
    Some(name.to_string())
}
