use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Generate plugin manifest constants from src/plugins/*/manifest.json
    let manifest_dir = Path::new("../src/submodule");
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("plugin_manifests.rs");

    let mut manifests = Vec::new();

    if manifest_dir.exists() {
        for entry in fs::read_dir(manifest_dir).unwrap().flatten() {
            let manifest_path = entry.path().join("manifest.json");
            if manifest_path.exists() {
                let content = fs::read_to_string(&manifest_path).unwrap();
                manifests.push(content);
            }
        }
    }

    let mut code = String::from("/// Embedded plugin manifests (generated by build.rs)\n");
    code.push_str("fn embedded_plugin_manifests() -> Vec<serde_json::Value> {\n");
    code.push_str("    vec![\n");
    for m in &manifests {
        code.push_str(&format!("        serde_json::from_str(r#\"{}\"#).unwrap(),\n", m.trim()));
    }
    code.push_str("    ]\n");
    code.push_str("}\n");

    fs::write(&dest, code).unwrap();

    tauri_build::build()
}
