// Auto-generated plugin registrations (generated by build.rs)
// Do not edit manually.

#[path = "amkr/mod.rs"]
pub mod amkr;
#[path = "browser_ext/mod.rs"]
pub mod browser_ext;
#[path = "clipboard_history/mod.rs"]
pub mod clipboard_history;
#[path = "git/mod.rs"]
pub mod git;
#[path = "music_player/mod.rs"]
pub mod music_player;
#[path = "page_notes/mod.rs"]
pub mod page_notes;
#[path = "system_monitor/mod.rs"]
pub mod system_monitor;

pub fn setup_all(app: &tauri::AppHandle) {
    amkr::setup(app);
    browser_ext::setup(app);
    clipboard_history::setup(app);
    git::setup(app);
    music_player::setup(app);
    page_notes::setup(app);
    system_monitor::setup(app);
}

// Discovered plugin commands: ["amkr::fetch_amkr_metrics", "amkr::generate_commit_message", "amkr::get_amkr_models", "amkr::set_amkr_unified_model", "amkr::start_amkr_ws", "amkr::stop_amkr_ws", "browser_ext::open_extension_dir", "browser_ext::launch_browser_with_extension", "clipboard_history::get_clipboard_history", "clipboard_history::copy_to_clipboard", "clipboard_history::delete_clipboard_entry", "clipboard_history::clear_clipboard_history", "music_player::get_media_info", "music_player::get_media_sessions", "music_player::select_media_session", "music_player::media_control", "music_player::get_lyrics", "page_notes::load_page_notes", "page_notes::save_page_notes", "page_notes::get_ws_port", "system_monitor::fetch_system_metrics"]
